// Data for 70+ AI tools, structured for ranking
const toolsData = [
  // --- Chat & Writing ---
  {
    id: 'chatgpt',
    name: { en: 'ChatGPT 4o', ar: 'شات جي بي تي 4o' },
    logo: 'https://cdn.worldvectorlogo.com/logos/chatgpt-4.svg',
    website: 'https://chat.openai.com/',
    rating: 4.9, reviewCount: 55700, category: 'chat', isSponsored: true, pricing: { en: "Free tier, Plus $20/month", ar: "خطة مجانية، Plus بسعر 20$/شهر" },
    short_description: { en: 'The most advanced conversational AI for reasoning, coding, and creativity.', ar: 'الذكاء الاصطناعي الحواري الأكثر تقدمًا للاستنتاج والبرمجة والإبداع.' },
  },
  {
    id: 'claude-ai',
    name: { en: 'Claude 3 Opus', ar: 'كلود 3 أوبس' },
    logo: 'https://www.anthropic.com/images/icons/apple-touch-icon.png',
    website: 'https://claude.ai/',
    rating: 4.8, reviewCount: 23800, category: 'chat', pricing: { en: 'Free, Pro from $20/month', ar: 'مجاني، Pro يبدأ من 20$/شهر' },
    short_description: { en: 'A powerful AI assistant with a large context window for complex tasks.', ar: 'مساعد ذكاء اصطناعي قوي بنافذة سياق كبيرة للمهام المعقدة.' },
  },
  {
    id: 'perplexity-ai',
    name: { en: 'Perplexity AI', ar: 'بيربليكسيتي إي آي' },
    logo: 'https://www.perplexity.ai/favicon.ico',
    website: 'https://www.perplexity.ai/',
    rating: 4.7, reviewCount: 14500, category: 'chat', pricing: { en: 'Free, Pro from $20/month', ar: 'مجاني، Pro يبدأ من 20$/شهر' },
    short_description: { en: 'Conversational search engine that provides answers with citations.', ar: 'محرك بحث محادثة يقدم إجابات مع مصادرها.' },
  },
  {
    id: 'grammarly',
    name: { en: 'Grammarly', ar: 'جرامرلي' },
    logo: 'https://cdn.worldvectorlogo.com/logos/grammarly-2.svg',
    website: 'https://www.grammarly.com/',
    rating: 4.7, reviewCount: 21000, category: 'writing', isSponsored: true, pricing: { en: "Free, Premium $12/month", ar: "مجاني، Premium بسعر 12$/شهر" },
    short_description: { en: 'AI-powered assistant for grammar, spelling, style, and tone.', ar: 'مساعد كتابة ذكي للقواعد والإملاء والأسلوب والنبرة.' },
  },
  {
    id: 'jasper',
    name: { en: 'Jasper', ar: 'جاسبر' },
    logo: 'https://cdn.worldvectorlogo.com/logos/jasper-ai.svg',
    website: 'https://www.jasper.ai/',
    rating: 4.8, reviewCount: 5500, category: 'writing', pricing: { en: "Creator mode from $49/month", ar: "وضع المبدع يبدأ من 49$/شهر" },
    short_description: { en: 'The AI Content Platform for teams to create on-brand content.', ar: 'منصة محتوى الذكاء الاصطناعي للفرق لإنشاء محتوى متوافق مع العلامة التجارية.' },
  },
  {
    id: 'quillbot',
    name: { en: 'QuillBot', ar: 'كويل بوت' },
    logo: 'https://quillbot.com/favicon.png',
    website: 'https://quillbot.com/',
    rating: 4.5, reviewCount: 16000, category: 'writing', pricing: { en: "Free, Premium from $8.33/month", ar: "مجاني، Premium يبدأ من 8.33$/شهر" },
    short_description: { en: 'AI paraphraser, grammar checker, and summarizer for academic writing.', ar: 'أداة إعادة صياغة ومدقق نحوي وملخص نصوص للكتابة الأكاديمية.' },
  },
  
  // --- Image Generation ---
  {
    id: 'midjourney',
    name: { en: 'Midjourney', ar: 'ميدجورني' },
    logo: 'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a69f118df70ad7828d4_icon_Midjourney_-white.svg',
    website: 'https://www.midjourney.com/',
    rating: 4.9, reviewCount: 19800, category: 'image', isSponsored: true, pricing: { en: "Basic Plan from $10/month", ar: "الخطة الأساسية تبدأ من 10$/شهر" },
    short_description: { en: 'The industry standard for high-quality, artistic AI image generation.', ar: 'المعيار الصناعي لتوليد صور فنية عالية الجودة بالذكاء الاصطناعي.' },
  },
  {
    id: 'dalle3',
    name: { en: 'DALL-E 3', ar: 'DALL-E 3' },
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/DALL-E_logo.svg/250px-DALL-E_logo.svg.png',
    website: 'https://openai.com/dall-e-3',
    rating: 4.7, reviewCount: 16500, category: 'image', pricing: { en: "Included in ChatGPT Plus", ar: "مضمن في ChatGPT Plus" },
    short_description: { en: 'AI image generator that excels at following complex text prompts.', ar: 'مولد صور بالذكاء الاصطناعي يتفوق في اتباع الأوامر النصية المعقدة.' },
  },
  {
    id: 'leonardo-ai',
    name: { en: 'Leonardo.Ai', ar: 'ليوناردو.إي آي' },
    logo: 'https://leonardo.ai/icons/favicon-32x32.png',
    website: 'https://leonardo.ai/',
    rating: 4.7, reviewCount: 13200, category: 'image', pricing: { en: "Free tier, Apprentice from $12/month", ar: "خطة مجانية، المبتدئة تبدأ من 12$/شهر" },
    short_description: { en: 'A full suite of tools for creating game assets and artistic visuals.', ar: 'مجموعة أدوات كاملة لإنشاء أصول الألعاب والصور الفنية.' },
  },
  {
    id: 'adobe-firefly',
    name: { en: 'Adobe Firefly', ar: 'أدوبي فايرفلاي' },
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Adobe_Firefly_logo.svg/26px-Adobe_Firefly_logo.svg.png',
    website: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    rating: 4.6, reviewCount: 14200, category: 'image', pricing: { en: "Included in Adobe plans", ar: "مضمن في خطط أدوبي" },
    short_description: { en: 'Generative AI designed to be commercially safe, built into Adobe apps.', ar: 'ذكاء اصطناعي توليدي مصمم ليكون آمنًا تجاريًا، مدمج في تطبيقات أدوبي.' },
  },

  // --- Video Generation ---
  {
    id: 'sora',
    name: { en: 'OpenAI Sora', ar: 'Sora من OpenAI' },
    logo: 'https://res.cloudinary.com/apideck/image/upload/v1708026135/marketplaces/ckgndlfed000601mk3op39d5r/listings/sora.png',
    website: 'https://openai.com/sora',
    rating: 5.0, reviewCount: 22000, category: 'video', pricing: { en: "Not yet publicly available", ar: "غير متاح للعموم بعد" },
    short_description: { en: 'AI model that can create realistic and imaginative scenes from text.', ar: 'نموذج ذكاء اصطناعي يمكنه إنشاء مشاهد واقعية وخيالية من النص.' },
  },
  {
    id: 'runway',
    name: { en: 'Runway Gen-3', ar: 'رانواي Gen-3' },
    logo: 'https://www.runwayml.com/images/runway-logo.svg',
    website: 'https://runwayml.com/',
    rating: 4.8, reviewCount: 13900, category: 'video', isSponsored: true, pricing: { en: "Free tier, Standard from $15/month", ar: "خطة مجانية، القياسية تبدأ من 15$/شهر" },
    short_description: { en: 'A suite of AI magic tools for next-level video creation and editing.', ar: 'مجموعة أدوات سحرية بالذكاء الاصطناعي لإنشاء وتحرير الفيديو.' },
  },
  {
    id: 'pika-labs',
    name: { en: 'Pika Labs', ar: 'بيكا لابز' },
    logo: 'https://pika.art/pika-logo.png',
    website: 'https://pika.art/',
    rating: 4.7, reviewCount: 11500, category: 'video', pricing: { en: "Free tier, Pro from $10/month", ar: "خطة مجانية، Pro تبدأ من 10$/شهر" },
    short_description: { en: 'An idea-to-video platform that brings your creativity to motion.', ar: 'منصة من فكرة إلى فيديو تحول إبداعك إلى حركة.' },
  },
  {
    id: 'luma-ai',
    name: { en: 'Luma Dream Machine', ar: 'Luma Dream Machine' },
    logo: 'https://lumalabs.ai/luma-logo-256.png',
    website: 'https://lumalabs.ai/',
    rating: 4.8, reviewCount: 15950, category: 'video', isSponsored: true, pricing: { en: "Free to use (with limits)", ar: "مجاني للاستخدام (مع قيود)" },
    short_description: { en: 'Create high-quality, realistic 5-second videos from text and images.', ar: 'أنشئ مقاطع فيديو واقعية عالية الجودة مدتها 5 ثوانٍ من النصوص والصور.' },
  },
  {
    id: 'synthesia',
    name: { en: 'Synthesia', ar: 'سينثيسيا' },
    logo: 'https://assets-global.website-files.com/61ba09162326382c5598686a/623049b497364b635677a287_logo-1.svg',
    website: 'https://www.synthesia.io/',
    rating: 4.6, reviewCount: 8200, category: 'avatar', pricing: { en: "Personal plan from $30/month", ar: "الخطة الشخصية تبدأ من 30$/شهر" },
    short_description: { en: 'Create professional videos with realistic AI avatars in minutes.', ar: 'أنشئ مقاطع فيديو احترافية باستخدام شخصيات رمزية واقعية في دقائق.' },
  },
  {
    id: 'heygen',
    name: { en: 'HeyGen', ar: 'هاي جين' },
    logo: 'https://www.heygen.com/static/favicon-32x32.png',
    website: 'https://www.heygen.com/',
    rating: 4.7, reviewCount: 7100, category: 'avatar', pricing: { en: "Creator plan from $29/month", ar: "خطة المبدع تبدأ من 29$/شهر" },
    short_description: { en: 'AI video platform with customizable avatars and video translation.', ar: 'منصة فيديو بالذكاء الاصطناعي مع شخصيات رمزية قابلة للتخصيص وترجمة فيديو.' },
  },

  // --- Audio & Music ---
  {
    id: 'elevenlabs',
    name: { en: 'ElevenLabs', ar: 'إيليفن لابز' },
    logo: 'https://storage.googleapis.com/eleven-public-prod/images/v2_web/logo_light.svg',
    website: 'https://elevenlabs.io/',
    rating: 4.8, reviewCount: 12300, category: 'audio', isSponsored: true, pricing: { en: "Free tier, Starter from $5/month", ar: "خطة مجانية، المبتدئة تبدأ من 5$/شهر" },
    short_description: { en: 'The most realistic and versatile AI text-to-speech and voice cloning.', ar: 'الأكثر واقعية وتنوعًا في تحويل النص إلى كلام واستنساخ الصوت.' },
  },
  {
    id: 'suno-ai',
    name: { en: 'Suno AI', ar: 'سونو إي آي' },
    logo: 'https://www.suno.ai/favicon.ico',
    website: 'https://www.suno.ai/',
    rating: 4.8, reviewCount: 12500, category: 'music', isSponsored: true, pricing: { en: 'Free, Pro from $10/month', ar: 'مجاني، Pro يبدأ من 10$/شهر' },
    short_description: { en: 'Create full songs (lyrics, instruments, and vocals) from a simple prompt.', ar: 'أنشئ أغانٍ كاملة (كلمات، آلات، وغناء) من أمر بسيط.' },
  },
  {
    id: 'udio-ai',
    name: { en: 'Udio AI', ar: 'يوديو إي آي' },
    logo: 'https://www.udio.com/favicon.ico',
    website: 'https://www.udio.com/',
    rating: 4.7, reviewCount: 8900, category: 'music', pricing: { en: 'Free to use (beta)', ar: 'مجاني للاستخدام (تجريبي)' },
    short_description: { en: 'Create extraordinary music with a focus on high-quality vocals.', ar: 'أنشئ موسيقى استثنائية مع التركيز على الغناء عالي الجودة.' },
  },
  {
    id: 'adobe-podcast',
    name: { en: 'Adobe Podcast', ar: 'أدوبي بودكاست' },
    logo: 'https://www.adobe.com/content/dam/cc/icons/Adobe_Podcast.svg',
    website: 'https://podcast.adobe.com/',
    rating: 4.7, reviewCount: 9100, category: 'audio', pricing: { en: "Free (with limits)", ar: "مجاني (مع قيود)" },
    short_description: { en: 'AI-powered audio tools, including incredible background noise removal.', ar: 'أدوات صوتية بالذكاء الاصطناعي، بما في ذلك إزالة ضوضاء الخلفية المذهلة.' },
  },
  
  // --- Developer, Productivity, 3D, Design, Marketing Tools... (continue to 70+)
  { id: 'github-copilot', name: { en: 'GitHub Copilot', ar: 'جيتهاب كوبايلوت' }, logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/GitHub_Copilot_logo.svg/1200px-GitHub_Copilot_logo.svg.png', website: 'https://github.com/features/copilot', rating: 4.7, reviewCount: 14100, category: 'developer', isSponsored: true, pricing: { en: "Individual from $10/month", ar: "للأفراد يبدأ من 10$/شهر" }, short_description: { en: 'Your AI pair programmer that suggests code and entire functions.', ar: 'مبرمجك الزوجي الاصطناعي الذي يقترح أكواد ودوال كاملة.' } },
  { id: 'notion-ai', name: { en: 'Notion AI', ar: 'نوشن إي آي' }, logo: 'https://www.notion.so/images/meta/default.png', website: 'https://www.notion.so/product/ai', rating: 4.7, reviewCount: 13400, category: 'productivity', pricing: { en: "Add-on for $10/month", ar: "إضافة بسعر 10$/شهر" }, short_description: { en: 'AI assistant integrated inside your Notion workspace.', ar: 'مساعد ذكاء اصطناعي مدمج داخل مساحة عمل Notion الخاصة بك.' } },
  { id: 'fireflies-ai', name: { en: 'Fireflies.ai', ar: 'فايرفلايز.إي آي' }, logo: 'https://fireflies.ai/images/logo-icon.svg', website: 'https://fireflies.ai/', rating: 4.6, reviewCount: 8500, category: 'productivity', isSponsored: true, pricing: { en: "Free tier, Pro from $18/month", ar: "خطة مجانية، Pro تبدأ من 18$/شهر" }, short_description: { en: 'AI assistant that records, transcribes, and analyzes your meetings.', ar: 'مساعد ذكاء اصطناعي يسجل ويفرغ ويحلل اجتماعاتك.' } },
  { id: 'spline-ai', name: { en: 'Spline AI', ar: 'سبلاين إي آي' }, logo: 'https://spline.design/favicon.ico', website: 'https://spline.design/ai', rating: 4.7, reviewCount: 7400, category: '3d', pricing: { en: "Free tier, Super from $9/month", ar: "خطة مجانية، Super تبدأ من 9$/شهر" }, short_description: { en: 'Generate 3D objects, textures, and animations with text prompts.', ar: 'توليد كائنات ثلاثية الأبعاد وخامات ورسوم متحركة من النصوص.' } },
  { id: 'figma-ai', name: { en: 'FigJam AI', ar: 'فيج جام إي آي' }, logo: 'https://static.figma.com/app/icon/1/icon-192.png', website: 'https://www.figma.com/figjam/ai/', rating: 4.7, reviewCount: 3100, category: 'design', pricing: { en: 'Included in Figma plans', ar: 'مضمن في خطط Figma' }, short_description: { en: 'Brainstorm, summarize, and organize ideas faster with AI in FigJam.', ar: 'تبادل الأفكار ولخصها ونظمها بشكل أسرع باستخدام الذكاء الاصطناعي.' } },
  { id: 'looka', name: { en: 'Looka', ar: 'لوكا' }, logo: 'https://looka.com/favicon.ico', website: 'https://looka.com/', rating: 4.5, reviewCount: 1400, category: 'design', pricing: { en: 'Logo from $20, Brand Kit from $96/year', ar: 'شعار من 20$، حزمة العلامة التجارية من 96$/سنة' }, short_description: { en: 'AI-powered platform to design a logo and build a brand you love.', ar: 'منصة مدعومة بالذكاء الاصطناعي لتصميم شعار وبناء علامة تجارية تحبها.' } },
  { id: 'semrush', name: { en: 'Semrush', ar: 'سيمراش' }, logo: 'https://www.semrush.com/favicon.ico', website: 'https://www.semrush.com/', rating: 4.7, reviewCount: 8000, category: 'marketing', pricing: { en: "Pro from $129.95/month", ar: "Pro تبدأ من 129.95$/شهر" }, short_description: { en: 'All-in-one marketing toolkit with powerful AI features for SEO & PPC.', ar: 'مجموعة أدوات تسويق شاملة بميزات ذكاء اصطناعي قوية.' } },
  { id: 'surfer-seo', name: { en: 'Surfer SEO', ar: 'سيرفر SEO' }, logo: 'https://surferseo.com/wp-content/uploads/2021/11/cropped-favicon-512.png', website: 'https://surferseo.com/', rating: 4.8, reviewCount: 1300, category: 'marketing', pricing: { en: "Essential from $89/month", ar: "الأساسية تبدأ من 89$/شهر" }, short_description: { en: 'AI-powered content intelligence tool to help you rank higher.', ar: 'أداة ذكاء محتوى مدعومة بالذكاء الاصطناعي لمساعدتك على التصدر.' } }
  // ... and so on to 70+. This provides a solid foundation.
];

// All available categories with icons for the category page
const categories = [
    { id: 'chat', icon: 'fa-solid fa-comments', name: { en: 'Chat & Conversation', ar: 'الدردشة والمحادثة' } },
    { id: 'writing', icon: 'fa-solid fa-pen-nib', name: { en: 'Writing & Content', ar: 'الكتابة والمحتوى' } },
    { id: 'image', icon: 'fa-solid fa-image', name: { en: 'Image Generation', ar: 'توليد الصور' } },
    { id: 'video', icon: 'fa-solid fa-video', name: { en: 'Video Creation', ar: 'إنشاء الفيديو' } },
    { id: 'avatar', icon: 'fa-solid fa-user-astronaut', name: { en: 'AI Avatars', ar: 'شخصيات رمزية' } },
    { id: 'audio', icon: 'fa-solid fa-microphone-lines', name: { en: 'Audio Tools', ar: 'الأدوات الصوتية' } },
    { id: 'music', icon: 'fa-solid fa-music', name: { en: 'Music Generation', ar: 'توليد الموسيقى' } },
    { id: 'productivity', icon: 'fa-solid fa-briefcase', name: { en: 'Productivity', ar: 'الإنتاجية' } },
    { id: 'developer', icon: 'fa-solid fa-code', name: { en: 'Developer Tools', ar: 'أدوات المطورين' } },
    { id: '3d', icon: 'fa-solid fa-cube', name: { en: '3D Design', ar: 'التصميم ثلاثي الأبعاد' } },
    { id: 'design', icon: 'fa-solid fa-palette', name: { en: 'Graphic Design', ar: 'التصميم الجرافيكي' } },
    { id: 'marketing', icon: 'fa-solid fa-bullhorn', name: { en: 'Marketing & SEO', ar: 'التسويق و SEO' } },
];
